### ISSUE TITLE
Make setting "awokado_debug" non-mandatory

### ISSUE THREAD

**Issue by tgrx** [5783354/awokado#3]
For what: for some reason this var is required to be explicitly set in config. For example:

```toml
[default]

awokado_debug = false
```

Can't imagine why one should explicitly set this var in production in the side project
